on:
  release:
    types: [released]

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build-and-publish:
    name: Build and publish release
    runs-on: ubuntu-latest
    permissions:
      # Required for publishing release artifacts
      contents: write
      # Required for PyPI trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v4

      # Note: uses .python-version file by default
      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: pip install --upgrade pip .[test,release]

      - name: Build wheel
        run: python -m pip wheel --no-deps . -w dist

      - name: Publish wheel to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Bundle JSON schemas
        run: zip -r dist/evo-schemas-${{ github.event.release.tag_name }}-schemas.zip schema

      - name: Upload wheel and JSON schemas to GitHub Release
        shell: bash
        run: gh release upload ${{ github.event.release.tag_name }} dist/*
