name: Unit tests

permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
  workflow_call:
  push:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip .[test]

      - name: Run unit tests
        run: python -m pytest --import-mode=append tests/
